name: Sync to Upstream

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push changes to upstream
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote add upstream https://x-access-token:${{ secrets.UPSTREAM_TOKEN }}@github.com/roabaot/nfsc.git
          git fetch upstream
          git merge upstream/main --no-edit
          git push upstream main:main
